### ISSUE TITLE
1.16没有设置和快捷键了吗

### ISSUE THREAD

**Issue by seantej** [CFPAOrg/I18nUpdateMod2#1]
reborn也没看到，2.0也没见到快捷键

**Comment by TartaricAcid** [comment]
鉴于以前曾经发生过的各种问题，目前模组的设计我想遵循 KISS 原则，做的又小又简单。所以不想加入任何快捷键和配置功能

**Comment by seantej** [comment]
> 鉴于以前曾经发生过的各种问题，目前模组的设计我想遵循 KISS 原则，做的又小又简单。所以不想加入任何快捷键和配置功能

感谢回答。
