### ISSUE TITLE
1.16.4中出现javafml36的问题

### ISSUE THREAD

**Issue by PiscesSoda** [CFPAOrg/I18nUpdateMod2#10]
![image](https://user-images.githubusercontent.com/61488102/116674766-583ca700-a9a5-11eb-8121-161ae21301e5.png)

[crash-2021-04-30_11.09.17-fml.txt](https://github.com/CFPAOrg/I18nUpdateMod2/files/6404247/crash-2021-04-30_11.09.17-fml.txt)
[latest.log](https://github.com/CFPAOrg/I18nUpdateMod2/files/6404248/latest.log)

**Comment by TartaricAcid** [comment]
字面意思，你的 forge 版本太低了而已，更新下 forge 版本就行

**Comment by PiscesSoda** [comment]
啊非常感谢（拜）
不是很懂这些代码
给您添麻烦了（笑）

**Comment by PiscesSoda** [comment]
我刚刚查了一下
forge版本也是最新的35.1.37
我尝试重新安装了forge也没有解决（苦笑）

**Comment by TartaricAcid** [comment]
你这是 1.16.4 啊，最新版 Minecraft 是 1.16.5 啊

**Comment by PiscesSoda** [comment]
欸！！抱歉！不好意思！
没有注意这个呢，那1.16.4版本是没有这个模组支持的对吧

**Comment by PiscesSoda** [comment]
将整合包升级到1.16.5就没问题了
问题解决（salute）
