### ISSUE TITLE
【汉化资源包下载失败】1.12.2-1.1.0

### ISSUE THREAD

**Issue by ghost** [CFPAOrg/I18nUpdateMod2#11]
启动加载mod时弹出来的对话框如下：
![is-img-01](https://user-images.githubusercontent.com/28667253/117992764-c142f800-b371-11eb-9c66-808b3dc464d1.png)
进入世界后：
![is-img-02](https://user-images.githubusercontent.com/28667253/117993020-f0596980-b371-11eb-936c-9725ef44e651.png)
请问大佬这个可能的原因是什么呢？
有需要挂代理的可能吗？

**Comment by ohohohoh1** [comment]
您好 请问一下您解决这个问题了吗- -我也遇到了这个问题

**Comment by liutingfenga** [comment]
您好 请问一下您解决这个问题了吗- -我也遇到了这个问题

**Comment by TartaricAcid** [comment]
应该是偶发性的网络波动而已
