### ISSUE TITLE
在安卓 Boat 环境下使用 l10nUpdate 1.12.2 版本会导致游戏崩溃

### ISSUE THREAD

**Issue by H4M5TER** [CFPAOrg/I18nUpdateMod2#12]
具体就是，开游戏载入的时候 l10nUpdate 会弹一个窗口检测和更新汉化，安卓环境下没法弹就跳异常了。
或许可以通过判断系统屏蔽这个弹窗来解决。
不知道这个问题是否存在于其他 MC 版本的 l10nUpdate。
1.12.2 那个 repo 不知道为什么 archived 了，所以只能发到这里了。

报错:

```log
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from I18n Update Mod (i18nmod)
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
```

[crash-2021-05-14_21.51.15-client.txt](https://github.com/CFPAOrg/I18nUpdateMod2/files/6481413/crash-2021-05-14_21.51.15-client.txt)

**Comment by TartaricAcid** [comment]
我滴妈，安卓……我用了 awt 库啊，没法解决，我只能保证在电脑上运行正常
