### ISSUE TITLE
1.16.5汉化失效

### ISSUE THREAD

**Issue by Minecraft-fish** [CFPAOrg/I18nUpdateMod2#19]
玩的是1.16.5的整合包Enigmatica6-0.4.14，汉化模组是最新的2.0.1，刚开始汉化都可以用，在与朋友局域网联机之后，汉化就失效了，而且重装整合包，汉化模组都不能解决问题，删除用户文件夹下的i18nupdatemod文件夹可以暂时解决问题，但是再次联机之后，汉化又会失效，我尝试把Minecraft-Mod-Language-Modpack-1-16这个压缩包复制到resourcepacks文件夹里，可以暂时解决联机汉化失效的问题。

**Comment by TartaricAcid** [comment]
问题已经过时
