### ISSUE TITLE
求求了   更新1.18的吧     我等不及了   拜托

### ISSUE THREAD

**Issue by lzj12138LZJ** [CFPAOrg/I18nUpdateMod2#29]
求求了   更新1.18的吧     我等不及了   拜托

**Comment by Gu-ZT** [comment]
https://github.com/CFPAOrg/I18nUpdateMod2/pull/32

**Comment by TartaricAcid** [comment]
正在处理中，请等待

**Comment by TartaricAcid** [comment]
https://github.com/CFPAOrg/I18nUpdateMod2/actions/runs/1891498311
