### ISSUE TITLE
请求整合一个mixin，能使patchouli加载外部资源包

### ISSUE THREAD

**Issue by kappa-maintainer** [CFPAOrg/I18nUpdateMod2#3]
@baka-gourd和我构思并实现了让帕秋莉优先加载资源包的mixin。这种外部修改已由他知会官方维护者并得到许可，但是因为一般需要和汉化资源包共同使用，现请求整合入i18n update mod。
具体代码：[链接](https://github.com/kappa-maintainer/PRP/blob/main/src/main/java/gkappa/prp/mixin/MixinBookContents.java)
同一repo下有编译好的[jar](https://github.com/kappa-maintainer/PRP/releases/tag/1.0)，可用于测试效果
细节方面，就是简单地使帕秋莉在加载json时优先从assets处，而不是data处加载。失败后回到正常行为，不影响现有功能，不受具体语言影响
缺点有：

1. 只有在data有现存json的时候才能加载assets的json，但对于资源包来说恰到好处
2. 依旧无法覆盖book.json

这些问题涉及高版本data和assets分离，我认为属于官方维护者的工作，故不进行进一步研究

**Comment by baka-gourd** [comment]
![image](https://user-images.githubusercontent.com/36119339/113890878-25185500-97f7-11eb-93e1-e3574d3a3617.png)

**Comment by baka-gourd** [comment]
@TartaricAcid

**Comment by TartaricAcid** [comment]
明白，我马上处理

**Comment by baka-gourd** [comment]
我新开了分支，已经处理好了
