### ISSUE TITLE
[BUG]偶尔会在游戏加载阶段出现错误导致游戏崩溃

### ISSUE THREAD

**Issue by ShunL12324** [CFPAOrg/I18nUpdateMod2#39]
https://gist.github.com/Eric-liucn/2595725f5b588bc40dc302814f6dcfb1 

![无法启动](https://s2.loli.net/2022/02/27/OEdh4exajUyDl1T.png)

**Comment by ShunL12324** [comment]
使用的是 1.16.5的最新的 2.0.3版本， Microsoft JDK 11

**Comment by TartaricAcid** [comment]
想办法处理中，主要这个 bug 是偶发性出现，难以定位原因

**Comment by Lxazl5770** [comment]
这个我也遇到过，需要降级到2.0.0才能解决问题

**Comment by Yukari316** [comment]
我也是遇到了一样的问题
[crash-2022-04-01_14.46.00-fml.txt](https://github.com/CFPAOrg/I18nUpdateMod2/files/8395327/crash-2022-04-01_14.46.00-fml.txt)

**Comment by ShiroAsrm** [comment]
同样的问题，发生于hotspot迁移至openj9后
https://gist.github.com/ShiroAsrm/7e5a9b6e2c103d8a1fb86fc4472a93d7

**Comment by TartaricAcid** [comment]
应该解决了
