### ISSUE TITLE
缓存问题的一个建议

### ISSUE THREAD

**Issue by SharpIceX** [CFPAOrg/I18nUpdateMod2#41]
使用
```Java
System.getProperty("user.home")
```
在部分Linux上会无法获取到用户文件夹（比如ArchLinux）

或许可以尝试使用
```Java
System.getProperty("java.io.tmpdir") 
```

**Comment by TartaricAcid** [comment]
为什么会有人用 Linux 啊，而且还是 ArchLinux

**Comment by SeraphJACK** [comment]
Linux 下无法复现。

**Comment by WhiredPlanck** [comment]
> 使用
> 
> ```java
> System.getProperty("user.home")
> ```
> 
> 在部分Linux上会无法获取到用户文件夹（比如ArchLinux）

这不太应该，这是 Java 获取操作系统主目录的标准方式。阁下或许需要考虑自己的系统环境（变量）是否有一些隐藏的影响。
