### ISSUE TITLE
[1.16.5]启动时崩溃

### ISSUE THREAD

**Issue by BrokenDawn627** [CFPAOrg/I18nUpdateMod2#42]
有时启动会崩 有时不会 不清楚原因
[crash-2022-05-01_13.53.59-fml.txt](https://github.com/CFPAOrg/I18nUpdateMod2/files/8598360/crash-2022-05-01_13.53.59-fml.txt)
[latest.log](https://github.com/CFPAOrg/I18nUpdateMod2/files/8598361/latest.log)

**Comment by Cyl18** [comment]
#39

**Comment by TartaricAcid** [comment]
应该已经解决了，试试最新版
