### ISSUE TITLE
崩溃 来自工单#CFPA-0702

### ISSUE THREAD

**Issue by Cyl18** [CFPAOrg/I18nUpdateMod2#43]
初步判断是 mixin 问题
[误报告-2022-6-6_12.08.46 (1).zip](https://github.com/CFPAOrg/I18nUpdateMod2/files/8886350/-2022-6-6_12.08.46.1.zip)

**Comment by TartaricAcid** [comment]
immersive industry 模组自己的问题，这模组也很近没见作者活跃了
