### ISSUE TITLE
未能加载有效的ResourcePackInfo

### ISSUE THREAD

**Issue by ghost** [CFPAOrg/I18nUpdateMod2#44]
![bk](https://user-images.githubusercontent.com/83486178/175196960-5847df16-ddfb-4823-8939-cb030aba7c3a.png)
[latest.log](https://github.com/CFPAOrg/I18nUpdateMod2/files/8963259/latest.log)
[debug.log](https://github.com/CFPAOrg/I18nUpdateMod2/files/8963260/debug.log)

**Comment by TartaricAcid** [comment]
这只是个提示，点击最下方按钮可以正常游戏

不过我也尝试修复下

**Comment by TartaricAcid** [comment]
已修复：https://github.com/CFPAOrg/I18nUpdateMod2/commit/b2c7793a335a07b007f4f3e0c207851396cb8ea3
