### ISSUE TITLE
建议使用 github + 加速源 作为镜像源分发下载资源包

### ISSUE THREAD

**Issue by zkitefly** [CFPAOrg/I18nUpdateMod2#57]
因为服务器压力过大，我的建议是使用 github  + 加速源 来分发下载资源包

**Comment by zkitefly** [comment]
我这边已经准备好了 https://github.com/zkitefly/TranslationPackMirror#readme

将所有链接的 `http://downloader1.meitangdehulu.com:22943/` 替换成 ~`https://ghproxy.com/https://raw.githubusercontent.com/zkitefly/TranslationPackMirror/main/files/`~`https://gitcode.net/chearlai/TranslationPackMirror/-/raw/main/files/`
不知可否？

**Comment by zkitefly** [comment]
这样可以解决 https://github.com/CFPAOrg/I18nUpdateMod2/issues/55 https://github.com/CFPAOrg/I18nUpdateMod2/issues/54  https://github.com/CFPAOrg/I18nUpdateMod2/issues/53 因为他们本质上就是下载速度过慢导致的

**Comment by Cyl18** [comment]
主要是能不能保证ghproxy的稳定性（都能访问）和下载文件都是最新
我感觉可以找个服务器放个json 动态请求下载地址 或者啥其它diff更新方法

**Comment by xfl03** [comment]
镜像源怕是受不了这么大流量，不觉得这是个合理的方案

**Comment by zkitefly** [comment]
> 主要是能不能保证ghproxy的稳定性（都能访问）和下载文件都是最新 我感觉可以找个服务器放个json 动态请求下载地址 或者啥其它diff更新方法

最新的这个问题，github-action会每一小时在没糖的服务器检查一次更新，如有更新就会同步

如果单个下载加速链接不行，那就多个，[此处](https://github.com/zkitefly/TranslationPackMirror#readme) 有说明多个下载加速链接的情况。

近期打算添加gitcode仓库下载地址，这个点速度和其他指数都很好

**Comment by zkitefly** [comment]
新消息，gitcode同步已经完成，gitcode的各项指标都非常棒：

![](https://api.onedrive.com/v1.0/shares/s!AiSrzi-vYVoBhB4PrXvES6IJLgNL/root/content)

![](https://api.onedrive.com/v1.0/shares/s!AiSrzi-vYVoBhCBXhWF2omNpPJP-/root/content)
```
zkitefly@zkitefly:~$ wget https://ghproxy.com/https://raw.githubusercontent.com/zkitefly/TranslationPackConvert/main/files/Minecraft-Mod-Language-Modpack-1-16T1-17.zip # ghproxy.com下载
--2023-01-14 16:09:33--  https://ghproxy.com/https://raw.githubusercontent.com/zkitefly/TranslationPackConvert/main/files/Minecraft-Mod-Language-Modpack-1-16T1-17.zip
正在解析主机 ghproxy.com (ghproxy.com)... 140.83.35.89
正在连接 ghproxy.com (ghproxy.com)|140.83.35.89|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：4724456 (4.5M) [application/zip]
正在保存至: “Minecraft-Mod-Language-Modpack-1-16T1-17.zip”

Minecraft-Mod-Language-Modp 100%[========================================>]   4.50M  5.49MB/s  用时 0.8s    

2023-01-14 16:09:36 (5.49 MB/s) - 已保存 “Minecraft-Mod-Language-Modpack-1-16T1-17.zip” [4724456/4724456])

已发出 HTTP 请求，正在等待回应... 301 Moved Permanently
位置：https://gitcode.net/chearlai/translationpackmirror/-/raw/main/files/Minecraft-Mod-Language-Modpack.zip [跟随至新的 URL]
--2023-01-14 17:42:47--  https://gitcode.net/chearlai/translationpackmirror/-/raw/main/files/Minecraft-Mod-Language-Modpack.zip
再次使用存在的到 gitcode.net:443 的连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：6878349 (6.6M) [application/zip]
正在保存至: “Minecraft-Mod-Language-Modpack.zip.3”

Minecraft-Mod-Lan 100%[============>]   6.56M  8.13MB/s  用时 0.8s    

2023-01-14 17:42:48 (8.13 MB/s) - 已保存 “Minecraft-Mod-Language-Modpack.zip.3” [6878349/6878349])


```

**Comment by meitangdehulu** [comment]
原有框架的更新和下载方式无法应对用户量激增，更换下载源和增加服务器实际上都是饮鸩止渴，只能解决短期的问题，gitee以前刚开始也是可以作为镜像站，但后续也是禁止库作为分发站点存在分发或者图床行为，国内商用带宽和流量费用高昂的客观情况，作为商业网站基本上都会控制这种纯下载的行为。
当然目前在分析完流量居高原因后也已经在对现有框架进行更迭，后续也将采取增量更新的方式替代完整更新，以降低服务器带宽占用。
