### ISSUE TITLE
1.16.5 I18漢化失效

### ISSUE THREAD

**Issue by Edel-Lilies** [CFPAOrg/I18nUpdateMod2#6]
本該有效的漢化條目從昨日開始全部變回原文

**Comment by TartaricAcid** [comment]
这几天是否正常？我会在 cf 上上传全新的版本

**Comment by Edel-Lilies** [comment]
每隔一段時間總會失效,不清楚原理,資源包加載頁面不存在.解決方法是去用戶文件夾刪除i18nupdatemod,然後重啟正常
