### ISSUE TITLE
1.16.5汉化突然失效

### ISSUE THREAD

**Issue by DSR117** [CFPAOrg/I18nUpdateMod2#7]
前几天安装mod后能正常工作如：匠魂；星辉；血魔法：XNet；循环；等mod汉化正常工作，在昨天夜晚与朋友第一次联机，这几个mod出现汉化失效的问题。直至今天单人档也成为了英文。

**Comment by TartaricAcid** [comment]
这几天是否正常了？

**Comment by noahlann** [comment]
并没有正常。。测试的是 Create 101 season II ，其中 Drawer 模组等汉化失效。
