### ISSUE TITLE
资源包缓存位置建议

### ISSUE THREAD

**Issue by reserveword** [CFPAOrg/I18nUpdateMod2#8]
现在的资源包全局缓存位置是`用户文件夹/.i18n/1.16/`，这意味着在用户文件夹下面单独设立一个文件夹。
可否考虑将缓存位置改为 `C:\Users\用户名\AppData\Roaming\.minecraft` 这一位置？据我所知这里似乎也是 minecraft 官方启动器默认工作路径，例如hmcl也在这一位置存储缓存内容。
https://github.com/CFPAOrg/I18nUpdateMod2/blob/64ed1f8c5fd463ea97fff389ac5afe9f4ba0caf3/src/main/java/com/github/tartaricacid/i18nupdatemod/I18nUpdateMod.java#L19

**Comment by TartaricAcid** [comment]
修改位置意义不大，因为所有的客户端都是读取同一位置的资源包，放哪里都是可行的
